- name: Apply MySQL common tasks to all
  hosts: all
  become: yes
  roles:
    - mysql_common

- name: Set up MySQL Server
  hosts: dbserver
  become: yes
  roles:
    - mysql_server

- name: Set up Backup Server
  hosts: backup
  become: yes
  roles:
    - backup_setup
