- name: Install and configure MySQL (Database Server)
  hosts: mysql_servers
  become: yes
  roles:
    - mysql

- name: Setup MySQL backups (Backup Server)
  hosts: backup
  become: yes
  roles:
    - role: mysql
      tasks_from: backup.yml
