mysql_root_password: "Welcome$24"
mysql_data_dir: "/var/lib/mysql"
mysql_config_file: "/etc/my.cnf"
mysql_rpm_bundle: "/tmp/mysql-9.1.0-1.el9.x86_64.rpm-bundle.tar"
mysql_temp_password_file: "/var/log/mysqld.log"
