- name: Copy MySQL Yum Repository RPM from control node
  ansible.builtin.copy:
    src: /tmp/mysql84-community-release-el9-1.noarch.rpm #make sure that the file is in this dir
    dest: /tmp/mysql84-community-release-el9-1.noarch.rpm
    mode: '0644'
    
- name: Install MySQL Yum Repository package
  ansible.builtin.dnf:
    name: /tmp/mysql84-community-release-el9-1.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Enable MySQL 8.4 repository
  ansible.builtin.command: dnf config-manager --set-enabled mysql-8.4-lts-community
  changed_when: false

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: present
