- name: Install MySQL Yum Repository package
  ansible.builtin.dnf:
    name: /tmp/mysql84-community-release-el9-1.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: Enable MySQL 8.4 repository
  ansible.builtin.command: dnf config-manager --set-enabled mysql-8.4-lts-community
  changed_when: false

- name: Install MySQL client
  ansible.builtin.dnf:
    name: mysql
    state: present
