- name: Ensure backup directory exists
  file:
    path: "{{ mysql_backup_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create MySQL backup script
  template:
    src: mysql_backup.sh.j2
    dest: "/usr/local/bin/mysql_backup.sh"
    mode: '0755'

- name: Set up cron job for backups
  cron:
    name: "MySQL Backup"
    job: "/usr/local/bin/mysql_backup.sh"
    minute: "0"
    hour: "2"
    user: root
