- name: Create MySQL database
  community.mysql.mysql_db:
    name: my_database
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  community.mysql.mysql_user:
    name: myuser
    password: "mypassword"
    priv: "my_database.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    plugin: mysql_native_password
