- name: Create application database
  community.mysql.mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: localhost

- name: Create application database user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    host: "{{ mysql_host }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: localhost
