---
- name: Get MySQL temporary root password
  shell: grep "temporary password" /var/log/mysqld.log | awk '{print $NF}' | tail -1
  register: mysql_temp_password
  changed_when: false
  failed_when: mysql_temp_password.rc != 0 or mysql_temp_password.stdout | length == 0

- name: Debug temporary password
  debug:
    msg: "MySQL temporary password: {{ mysql_temp_password.stdout }}"

- name: Set initial root password (handle expired password first)
  shell: |
    mysql --connect-expired-password -u root -p'{{ mysql_temp_password.stdout }}' -e "
      ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
  register: password_reset_result
  changed_when: password_reset_result.rc == 0
  failed_when: password_reset_result.rc != 0

- name: Debug password reset result
  debug:
    var: password_reset_result
  when: password_reset_result is defined

- name: Force root to use password auth
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    plugin: mysql_native_password
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    
