- name: Get temporary MySQL root password from log
  shell: |
    grep 'temporary password' "{{ mysql_temp_password_file }}" | awk '{print $NF}' | tail -1
  register: mysql_temp_password
  changed_when: false
  failed_when: mysql_temp_password.rc != 0
  no_log: true   # hide the sensitive password in output

- name: Set initial strong root password (handle expired password)
  shell: |
    mysql --connect-expired-password -u root -p'{{ mysql_temp_password.stdout }}' \
      -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_strong_password }}';"
  register: set_strong_password
  changed_when: set_strong_password.rc == 0
  no_log: true

- name: Set final root password (if different from strong password)
  shell: |
    mysql -u root -p'{{ mysql_strong_password }}' \
      -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
  register: set_final_password
  changed_when: set_final_password.rc == 0
  when: "{{ mysql_root_password != mysql_strong_password }}"
  no_log: true

- name: Create MySQL root config file (/root/.my.cnf)
  copy:
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
    content: |
      [client]
      user=root
      password={{ mysql_root_password }}
      host=localhost
