- name: Initialize MySQL data directory
  command: mysqld --initialize-insecure --user=mysql --datadir=/var/lib/mysql
  args:
    creates: /var/lib/mysql/mysql
    
- name: Get MySQL temporary root password
  shell: "grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'"
  register: mysql_temp_password
  changed_when: false

- name: Change MySQL root password (Handle Expired Password)
  shell: |
    mysql --connect-expired-password -u root -p'{{ mysql_temp_password.stdout }}' -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';"
  register: mysql_password_reset
  changed_when: mysql_password_reset.rc == 0
