- name: Ensure MySQL 8.4 repository is enabled
  ansible.builtin.dnf:
    name: mysql-8.4-community-release
    state: present

- name: Install MySQL 8.4 server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Enable and start MySQL service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started
