- name: Disable MySQL 8.0 repository
  command: dnf config-manager --disable mysql80-community

- name: Enable MySQL 8.4 repositories
  command: dnf config-manager --set-enabled mysql-8.4-lts-community mysql-tools-8.4-lts-community

- name: Install MySQL 8.4 Server
  dnf:
    name: mysql-server
    state: present

- name: Enable and Start MySQL Service
  service:
    name: mysqld
    enabled: yes
    state: started
