- name: Enable MySQL 8.4 module on RHEL 9
  command: dnf module enable -y mysql:8.4
  args:
    warn: false

- name: Install MySQL 8.4 server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Enable and start MySQL service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started
