- name: Install MySQL 8.4 Community Repository
  dnf:
    name: /tmp/mysql84-community-release.rpm
    state: present
    disable_gpg_check: yes

- name: Enable MySQL Community repository
  command: dnf config-manager --set-enabled mysql84-community

- name: Install MySQL 8.4 Server
  dnf:
    name: mysql-server
    state: present

- name: Enable and Start MySQL Service
  service:
    name: mysqld
    enabled: yes
    state: started
