- name: Add MySQL 8.4 Community Repository
  ansible.builtin.dnf:
    name: "https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm"
    state: present

- name: Enable MySQL Community repository
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled mysql80-community

- name: Install MySQL 8.4 server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Enable and start MySQL service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: started
