- name: Create MySQL backup script
  copy:
    dest: "/usr/local/bin/mysql_backup.sh"
    content: |
      #!/bin/bash
      mysqldump -u root -p'{{ mysql_root_password }}' my_database > /backups/my_database_$(date +\%F).sql
  mode: '0755'

- name: Set up cron job for backups
  cron:
    name: "MySQL Backup"
    job: "/usr/local/bin/mysql_backup.sh"
    minute: "0"
    hour: "2"
    user: root
