- name: Install and configure MySQL
  hosts: mysql_servers
  become: yes
  roles:
    - mysql

- name: Secure MySQL
  hosts: mysql_servers
  become: yes
  roles:
    - secure

- name: Setup MySQL backups
  hosts: backup
  become: yes
  roles:
    - backup
